version: '3.8'

services:
  nexea-backend:
    image: gcr.io/my-project-nexea/nexea-event-app-backend:latest
    container_name: nexea-backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgres://postgres:oneminuteplease@34.87.1.242:5432/nexea
    networks:
      - nexea

  nexea-frontend:
    image: gcr.io/my-project-nexea/nexea-event-app-frontend:latest
    container_name: nexea-frontend
    ports:
      - "3031:3031"
    networks:
      - nexea

  nginx:
    build: ./nginx
    ports:
      - "81:80"
    restart: always
    networks:
      - nexea

networks:
  nexea:
    driver: bridge

