FROM node:18.18.0-bullseye-slim AS development

WORKDIR /app

COPY ./package.json .

COPY . .

RUN yarn install 

RUN npx prisma generate

RUN yarn build

FROM node:18.18.0-bullseye-slim AS staging

WORKDIR /app

COPY ./package.json .

RUN yarn install --production

COPY --from=development /app/dist .

RUN npx prisma generate

EXPOSE 3001

CMD [ "node", "app.js" ]

